package com.oliversoft.blacksmith.model.enumeration;

public enum TaskStatus {
    DEV_PENDING, DEV_IN_PROGRESS, DEV_DONE, DEV_SKIPPED, DEV_FAILED, TEST_IN_PROGRESS, TEST_FAILED, TEST_PASSED, DEPLOY_IN_PROGRESS, DEPLOY_DONE, DEPLOY_FAILED, TEST_SKIPPED, TEST_PENDING, DEPLOY_PENDING
}